### ISSUE TITLE
Misnamed import when trying to import a default class

### ISSUE THREAD

**Issue by 5angel** [Microsoft/tslint-microsoft-contrib#387] opened 2017-08-22 10:49 UTC
It expects default imports to start with a lower case letter, but that in turn contradicts the common rule of writing classes with a first upper case letter.

**Comment by 5angel** [comment] 2018-04-04 10:48
@iamjoshhansen your example is actually ok, it's expected to name your files as your classes.

What I forgot to mention is that this rule also applies to packages as well.

Say, you're importing a lib named `foo-bar`, but it is actually a FooBar class.
So you'll want something like `import FooBar from 'foo-bar'`.
That will trigger an error in tslint.

**Comment by JoshuaKGoldberg** [comment] 2018-07-06 05:46
> It seems to follow the filename of the import.
> filename

Yes, this is a problem. Rules shouldn't work differently depending on whether the OS is case sensitive or case insensitive for file names. We should ignore name casing.

Duplicate of #430.

**Closed by JoshuaKGoldberg** 2018-07-06 05:46 UTC

**Comment by massimonewsuk** [comment] 2018-07-06 09:47
I like what @5angel suggested about allowing you to start imports with a capital letter (`import FooBar` as opposed to `import fooBar`), however I can also see a small downside around developer experience. For example typescript auto-suggests imports based on file names. So if you type `let x = new fooBar` then typescript will suggest importing `fooBar` from `./foo-bar`, but it won't suggest it if you had written `new FooBar`. So I guess the linting is currently aligned closely with how the TypeScript compiler expects people to reference these default exports, which is a good thing because it means a more consistent developer experience. However I do agree in that it's extremely odd to import a class with a lowercase letter to satisfy a linting rule.

@JoshuaKGoldberg Maybe we should ask the TypeScript guys to suggest the import to start with an uppercase letter if the default export was a class?

**Comment by villelahdenvuo** [comment] 2019-04-12 12:25
@JoshuaKGoldberg This is actually not a duplicate of #430 and not fixed by #451. If I have a default export `export default class User {...}` and try to import it: `import User from './models/user';` tslint complains. `Misnamed import. Import should be named 'user' but found 'User' (import-name)` unless I rename the file to User.ts. So like in **export**-name in #430 there should be ignore-case option for the **import**-name rule.
